import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./components/Providers";
import { prisma } from "@/lib/prisma";
import type { TeamMember, StepEntry } from "./types";

// Prevent static prerendering – all pages require live DB access at request time
export const dynamic = 'force-dynamic';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function getDefaultStartDate(): string {
  const now = new Date();
  return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-01`;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [membersRaw, entriesRaw, configs] = await Promise.all([
    prisma.member.findMany({ orderBy: { name: 'asc' } }),
    prisma.stepEntry.findMany({ orderBy: { date: 'asc' } }),
    prisma.config.findMany(),
  ]);

  const members: TeamMember[] = membersRaw.map(m => ({
    id: m.id, name: m.name, color: m.color, bgColor: m.bgColor,
  }));

  const entries: StepEntry[] = entriesRaw.map(e => ({
    memberId: e.memberId,
    date: e.date,
    steps: e.steps,
    proofDriveFileId: e.proofDriveFileId ?? undefined,
    proofDriveUrl: e.proofDriveUrl ?? undefined,
    hasLocalProof: e.hasLocalProof,
  }));

  const startDate = configs.find(c => c.key === 'startDate')?.value ?? getDefaultStartDate();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers initialData={{ members, entries, startDate }}>{children}</Providers>
      </body>
    </html>
  );
}
