// Client-side Excel service — delegates all heavy lifting to Next.js API routes.
import { TeamMember, ExcelRowParsed } from '../types';

export interface ColumnMap {
  nameCol: number;
  dateCol: number;
  stepsCol: number;
}

export interface ExcelParseResult {
  headers: string[];
  rows: unknown[][];
  columnMap: ColumnMap | null;
  parsedRows: ExcelRowParsed[];
  sheetNames: string[];
  totalRows: number;
}

/** Parse an Excel file by uploading it to the server API */
export async function parseExcelFile(
  buffer: ArrayBuffer,
  members: TeamMember[],
  sheetIndex = 0
): Promise<ExcelParseResult> {
  const form = new FormData();
  form.append('file', new Blob([buffer], { type: 'application/octet-stream' }), 'upload.xlsx');
  form.append('members', JSON.stringify(members));
  form.append('sheetIndex', String(sheetIndex));

  const res = await fetch('/api/excel/parse', { method: 'POST', body: form });
  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error((err as { error?: string }).error ?? 'Excel parse failed');
  }
  return res.json();
}

/** Download an Excel template generated by the server */
export async function generateExcelTemplate(members: TeamMember[]): Promise<void> {
  const res = await fetch('/api/excel/template', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ members }),
  });
  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error((err as { error?: string }).error ?? 'Template generation failed');
  }
  const blob = await res.blob();
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'step_tracker_template.xlsx';
  a.click();
  URL.revokeObjectURL(url);
}

